# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [ --branch, main ]
      - id: forbid-submodules
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
        exclude: \.(txt|jinja|svg)$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
